CREATE TABLE IF NOT EXISTS grupo_armado(
    codigoG INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nomeGrupo VARCHAR(30) NOT NULL,
    numBaixasG INT UNSIGNED,
    nroDivisao INT UNSIGNED NOT NULL,
    PRIMARY KEY(codigoG)
)




